### PR TITLE
Release 3.3.1 (latest)

### PR DESCRIPTION
**Pull request by mfisher87**
Supersedes #6

This skips a lot of versions, sadly. It's a heavy lift, unless someone knows of a tool to help!

* Add new maintainers from `pdgstaging` team (https://github.com/PermafrostDiscoveryGateway/viz-staging). @rushirajnenuji can you please comment in this PR to confirm your willingness to be a maintainer?
* Group often-changed values at top (personal preference)
* Adjust requirements and build script (grayskull)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfisher87** [comment]
@conda-forge-admin, please rerender

**Comment by rushirajnenuji** [comment]
Hi, I'm willing to be a maintainer for this.

**Comment by mfisher87** [comment]
@h-vetinari I think we're ready for a review :)

**Comment by h-vetinari** [comment]
> This skips a lot of versions, sadly. It's a heavy lift, unless someone knows of a tool to help!

If you want to publish some intermediate versions, the easiest way to do it would be to modify this PR (or another) to first update to 1.6, merge it, then open & merge another PR for 2.0, and 2.1, and 3.0 ... (random selection for arguments' sake), before you finally upgrade to the latest version.

**Review by h-vetinari — APPROVED** [review]
PR looks fine - thank you! Please let me know how you want to go about the intervening versions.

**Comment by mfisher87** [comment]
@h-vetinari thanks for your review! For our use case we don't need intervening versions, and as a maintainer on other feedstocks I've never had to deal with that problem. To kick that ball back in your court: do community standards demand that we deal with intervening versions or is it OK to wait for user need to be expressed?

**Comment by h-vetinari** [comment]
> do community standards demand that we deal with intervening versions or is it OK to wait for user need to be expressed?

No, it's not a requirement. It's already great that you're taking over maintenance from now on! And in the unlikely case that someone _desperately_ needs a version before 3.3.1, we can create a branch here and still publish an old version even after merging this PR (and without messing up the `main` branch).

**Comment by mfisher87** [comment]
> No, it's not a requirement. It's already great that you're taking over maintenance from now on! And in the unlikely case that someone desperately needs a version before 3.3.1, we can create a branch here and still publish an old version even after merging this PR (and without messing up the main branch).

Thanks for clarifying that and for explaining how we can go about that. Sounds a lot like how pre-releases work too. I've been considering a pre-release branch for the Quarto feedstock for some time now, but haven't got around to try it :)

**Comment by h-vetinari** [comment]
> Sounds a lot like how pre-releases work too.

Both are published from a separate branch, but some differences:
 * prerelease branches (should) publish to a separate label, not to main channel; maintenance branches publish to main channel
 * there's usually only ever one `rc` branch (that gets continuously updated), whereas there can be many maintenance branches, which eventually stay untouched after no more new (patch) releases targetting that old version get published.

There are many examples that use maintenance branches, as one that does it extensively, check out [arrow](https://github.com/conda-forge/arrow-cpp-feedstock)

**Comment by mfisher87** [comment]
Amazing. My mental model feels much more solid now. Special thanks for the example :heart:

**Pull request merged**
